import { StyleSheet, Platform, StatusBar } from 'react-native';

export const COLORS = {
  primary: '#4f46e5',
  background: '#09090b',
  card: 'rgba(24, 24, 27, 0.6)',
  border: '#27272a',
  textMain: '#fff',
  textSub: '#a1a1aa',
  textMuted: '#71717a',
  accentPurple: '#a78bfa',
  accentEmerald: '#34d399',
  accentRose: '#fb7185',
  zinc800: '#27272a',
  zinc900: '#18181b',
};

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#09090b',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight + 8 : 0 
  },
  scrollView: { flex: 1 },
  scrollContent: { 
    padding: 16, 
    paddingBottom: Platform.OS === 'ios' ? 120 : 100, 
    flexGrow: 1 
  },
  screenContent: { flex: 1, display: 'flex', flexDirection: 'column' },
  row: { flexDirection: 'row', alignItems: 'center' },
  centerAll: { alignItems: 'center', justifyContent: 'center' },
  bgEmerald: { backgroundColor: '#10b981' },
  bgRose: { backgroundColor: '#f43f5e' },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  logoIcon: { backgroundColor: '#6366f1', padding: 10, borderRadius: 16, marginRight: 12 },
  logoText: { color: '#fff', fontSize: 22, fontWeight: '900', letterSpacing: -0.5 },
  logoSubtext: { color: '#a1a1aa', fontSize: 10, fontWeight: '700', letterSpacing: 1.5 },
  btnBluetooth: { padding: 12, backgroundColor: 'rgba(39, 39, 42, 0.6)', borderRadius: 16, borderWidth: 1, borderColor: '#27272a' },
  btnBluetoothActive: { backgroundColor: 'rgba(99, 102, 241, 0.1)', borderColor: 'rgba(99, 102, 241, 0.3)' },
  heroCard: { backgroundColor: 'rgba(24, 24, 27, 0.8)', borderRadius: 24, padding: 24, borderWidth: 1, borderColor: '#27272a', marginBottom: 16 },
  heroHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 },
  badge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, borderWidth: 1 },
  badgeBlue: { backgroundColor: 'rgba(59, 130, 246, 0.1)', borderColor: 'rgba(59, 130, 246, 0.2)' },
  badgeEmerald: { backgroundColor: 'rgba(16, 185, 129, 0.1)', borderColor: 'rgba(16, 185, 129, 0.2)' },
  badgeZinc: { backgroundColor: 'rgba(63, 63, 70, 0.5)', borderColor: '#3f3f46' },
  dotPulse: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#3b82f6', marginRight: 8 },
  badgeTextBlue: { color: '#60a5fa', fontSize: 12, fontWeight: '700' },
  badgeTextEmerald: { color: '#34d399', fontSize: 12, fontWeight: '700', marginLeft: 6 },
  badgeTextZinc: { color: '#a1a1aa', fontSize: 12, fontWeight: '700', marginLeft: 6 },
  subText: { color: '#a1a1aa', fontSize: 12, marginLeft: 6, fontWeight: '500' },
  btnSync: { backgroundColor: '#4f46e5', padding: 14, borderRadius: 16 },
  btnSyncDisabled: { backgroundColor: '#27272a' },
  heroMain: { flexDirection: 'row', alignItems: 'flex-end', gap: 12 },
  heroBpmText: { color: '#fff', fontSize: 64, fontWeight: '900', letterSpacing: -2, lineHeight: 70 },
  heroBpmLabel: { color: '#a1a1aa', fontSize: 16, fontWeight: '700' },
  heroBpmSublabel: { color: '#71717a', fontSize: 10, fontWeight: '600', textTransform: 'uppercase' },
  diagContainer: { backgroundColor: 'rgba(39, 39, 42, 0.3)', borderRadius: 24, padding: 20, borderWidth: 1, borderColor: '#27272a', marginBottom: 20 },
  diagMainTitle: { color: '#fff', fontSize: 15, fontWeight: '800' },
  diagLiveBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(16, 185, 129, 0.1)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  diagLiveText: { color: '#34d399', fontSize: 10, fontWeight: '900', marginLeft: 6 },
  dotPulseGreen: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#10b981' },
  diagGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  diagItem: { alignItems: 'center', flex: 1 },
  diagLabel: { color: '#71717a', fontSize: 10, fontWeight: '600', marginTop: 4, textTransform: 'uppercase' },
  diagValue: { color: '#fff', fontSize: 14, fontWeight: '700', marginTop: 2 },
  electrodesBox: { borderTopWidth: 1, borderTopColor: '#27272a', paddingTop: 16 },
  electrodesTitle: { color: '#a1a1aa', fontSize: 12, fontWeight: '600', marginBottom: 12 },
  electrodeItem: { flexDirection: 'row', alignItems: 'center', marginRight: 16 },
  electrodeDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
  electrodeName: { color: '#d4d4d8', fontSize: 11, fontWeight: '500' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 12 },
  statCard: { width: '48%', backgroundColor: 'rgba(24, 24, 27, 0.6)', borderRadius: 20, padding: 16, borderWidth: 1, borderColor: '#27272a', justifyContent: 'space-between' },
  statIconBg: { backgroundColor: '#27272a', padding: 8, borderRadius: 12, alignSelf: 'flex-start', marginBottom: 12 },
  statValue: { color: '#fff', fontSize: 20, fontWeight: '900' },
  statUnit: { color: '#71717a', fontSize: 12, fontWeight: '600' },
  statLabel: { color: '#a1a1aa', fontSize: 11, fontWeight: '500', marginTop: 4 },
  chartContainer: { backgroundColor: 'rgba(24, 24, 27, 0.6)', borderRadius: 24, padding: 20, borderWidth: 1, borderColor: '#27272a', height: 240 }, 
  chartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  chartTitle: { color: '#d4d4d8', fontSize: 13, fontWeight: '600', marginLeft: 8 },
  chartBadge: { backgroundColor: 'rgba(139, 92, 246, 0.1)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  chartBadgeText: { color: '#c4b5fd', fontSize: 11, fontWeight: '700' },
  svgWrapper: { flex: 1, overflow: 'visible' },
  emptyIconBg: { backgroundColor: '#27272a', padding: 16, borderRadius: 30, marginBottom: 12 },
  emptyTextTitle: { color: '#a1a1aa', fontSize: 14, fontWeight: '600' },
  emptyTextSub: { color: '#71717a', fontSize: 12, marginTop: 4 },
  bottomAction: { marginTop: 'auto', paddingTop: 32 },
  btnPrimary: { backgroundColor: '#4f46e5', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 18, borderRadius: 20, gap: 12 },
  btnPrimaryDisabled: { backgroundColor: '#27272a' },
  btnPrimaryText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  btnPrimaryTextDisabled: { color: '#52525b' },
  btnSecondary: { backgroundColor: '#27272a', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 16, borderRadius: 16, marginBottom: 12, borderWidth: 1, borderColor: '#3f3f46' },
  btnSecondaryText: { color: '#fff', fontSize: 14, fontWeight: '700', marginLeft: 8 },
  pageHeader: { marginBottom: 24, marginTop: 8 },
  pageTitle: { color: '#fff', fontSize: 28, fontWeight: '900' },
  pageSubtitle: { color: '#a1a1aa', fontSize: 13, marginTop: 4 },
  historyCard: { backgroundColor: 'rgba(24, 24, 27, 0.6)', borderWidth: 1, borderColor: '#27272a', borderRadius: 20, padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  historyIconBg: { backgroundColor: '#27272a', padding: 12, borderRadius: 14 },
  historyDate: { color: '#f4f4f5', fontSize: 16, fontWeight: '700' },
  historyBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#27272a', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  historyBadgeText: { color: '#a1a1aa', fontSize: 11, fontWeight: '600', marginLeft: 4 },
  historyAlertBadge: { backgroundColor: 'rgba(244, 63, 94, 0.1)', padding: 6, borderRadius: 10, marginRight: 8 },
  sectionTitle: { color: '#71717a', fontSize: 11, fontWeight: '700', letterSpacing: 1, marginLeft: 8, marginBottom: 12 },
  settingCard: { backgroundColor: 'rgba(24, 24, 27, 0.6)', borderRadius: 20, borderWidth: 1, borderColor: '#27272a', paddingHorizontal: 16, marginBottom: 16, overflow: 'hidden' },
  settingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, minHeight: 64 },
  settingBorderBottom: { borderBottomWidth: 1, borderBottomColor: '#27272a' },
  settingIconBg: { padding: 10, borderRadius: 12, backgroundColor: '#27272a' },
  settingIconBgActive: { backgroundColor: 'rgba(99, 102, 241, 0.2)' },
  settingTitle: { color: '#fff', fontSize: 15, fontWeight: '700' },
  settingSub: { color: '#a1a1aa', fontSize: 12, marginTop: 2 },
  toggleTrack: { width: 44, height: 26, borderRadius: 13, backgroundColor: '#27272a', borderWidth: 1, borderColor: '#3f3f46', justifyContent: 'center', padding: 2 },
  toggleTrackActive: { backgroundColor: '#4f46e5', borderColor: '#6366f1' },
  toggleThumb: { width: 20, height: 20, borderRadius: 10, backgroundColor: '#fff' },
  toggleThumbActive: { transform: [{ translateX: 18 }] },
  reportNavRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  btnBack: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#18181b', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, borderWidth: 1, borderColor: '#27272a' },
  btnBackText: { color: '#a1a1aa', fontWeight: '600', marginLeft: 4 },
  patientBadge: { backgroundColor: '#18181b', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, borderWidth: 1, borderColor: '#27272a' },
  patientBadgeText: { color: '#71717a', fontSize: 10, fontWeight: '700', letterSpacing: 1 },
  reportCard: { backgroundColor: 'rgba(24, 24, 27, 0.8)', borderRadius: 24, padding: 20, borderWidth: 1, borderColor: '#27272a' },
  reportHeader: { borderBottomWidth: 1, borderBottomColor: '#27272a', paddingBottom: 20, marginBottom: 20 },
  reportTitle: { color: '#fff', fontSize: 22, fontWeight: '900', marginLeft: 12 },
  reportSub: { color: '#a1a1aa', fontSize: 13, fontWeight: '500' },
  tableCard: { backgroundColor: '#18181b', borderRadius: 16, borderWidth: 1, borderColor: '#27272a', overflow: 'hidden', marginBottom: 24 },
  tableHeader: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#27272a', padding: 12 },
  tableHeaderText: { color: '#fff', fontSize: 11, fontWeight: '700', letterSpacing: 1, marginLeft: 8 },
  tableRow: { flexDirection: 'row', justifyContent: 'space-between', padding: 12, borderBottomWidth: 1, borderBottomColor: '#27272a' },
  tableCellLabel: { color: '#a1a1aa', fontSize: 13 },
  tableCellValue: { color: '#fff', fontSize: 14, fontWeight: '700' },
  sectionTitleAi: { color: '#fff', fontSize: 18, fontWeight: '700', marginLeft: 12 },
  iconBgEmerald: { backgroundColor: 'rgba(52, 211, 153, 0.1)', padding: 6, borderRadius: 8 },
  aiBox: { backgroundColor: 'rgba(39, 39, 42, 0.4)', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#27272a', marginTop: 16 },
  aiText: { color: '#d4d4d8', fontSize: 13, lineHeight: 20 },
  aiBoxTitle: { color: '#fff', fontSize: 14, fontWeight: '700', marginBottom: 12 },
  aiListItem: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
  aiListText: { color: '#d4d4d8', fontSize: 13, marginLeft: 8, flex: 1 },
  warningBox: { backgroundColor: 'rgba(244, 63, 94, 0.1)', borderRadius: 16, padding: 16, borderLeftWidth: 4, borderLeftColor: '#f43f5e', marginTop: 24 },
  warningTitle: { color: '#fb7185', fontSize: 13, fontWeight: '700', marginLeft: 8 },
  warningText: { color: '#fecdd3', fontSize: 13, marginTop: 8, lineHeight: 20 },
  ecgContainer: { marginBottom: 24 },
  ecgHeader: { marginBottom: 12 },
  ecgTitle: { color: '#fff', fontSize: 14, fontWeight: '700', marginLeft: 8 },
  ecgDescription: { color: '#a1a1aa', fontSize: 11, marginTop: 4 },
  ecgBadgesRow: { flexDirection: 'row', gap: 8, marginTop: 8 },
  ecgBadgeDark: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#27272a', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  ecgBadgeTextDark: { color: '#d4d4d8', fontSize: 11, fontWeight: '600', marginLeft: 4 },
  ecgBadgeRose: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(244, 63, 94, 0.1)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  ecgBadgeTextRose: { color: '#fb7185', fontSize: 11, fontWeight: '600', marginLeft: 4 },
  ecgSvgWrapper: { height: 140, backgroundColor: '#09090b', borderRadius: 16, borderWidth: 1, borderColor: '#27272a', overflow: 'hidden' },
  emailForm: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#18181b', borderRadius: 16, borderWidth: 1, borderColor: '#27272a' },
  input: { flex: 1, color: '#fff', paddingVertical: 14, paddingHorizontal: 12, fontSize: 14 },
  btnSend: { backgroundColor: '#4f46e5', padding: 14, borderRadius: 12, margin: 4 },
  bottomNav: { position: 'absolute', bottom: 0, width: '100%', flexDirection: 'row', backgroundColor: 'rgba(9, 9, 11, 0.95)', borderTopWidth: 1, borderTopColor: '#27272a', paddingBottom: Platform.OS === 'ios' ? 24 : 16, paddingTop: 12 },
  navItem: { flex: 1, alignItems: 'center' },
  navText: { color: '#71717a', fontSize: 10, fontWeight: '700', marginTop: 4, letterSpacing: 0.5 },
  navTextActive: { color: '#818cf8' },
  toast: { position: 'absolute', bottom: Platform.OS === 'ios' ? 100 : 80, left: 20, right: 20, backgroundColor: '#18181b', flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 16, borderWidth: 1, borderColor: '#27272a', shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.5, shadowRadius: 15, elevation: 10 },
  toastError: { backgroundColor: '#4c0519', borderColor: '#881337' },
  toastSuccess: { backgroundColor: '#022c22', borderColor: '#064e3b' },
  toastInfo: { backgroundColor: '#18181b', borderColor: '#27272a' },
  toastText: { color: '#fff', fontSize: 13, fontWeight: '500', marginLeft: 12, flex: 1 },
});